CUDA_VISIBLE_DEVICES=0 nohup python -u main_eval_all.py --data datasets/cifar10 --dataset cifar10 --arch res18 --save_dir res18_cifar10_extreme_qrcode --pretrained pretrained_model/resnet18_lt_cifar10.pt --mask_dir ownership/res18_cifar10_qrcode_layer3.0.conv1.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar10_extreme_qrcode_layer3.0.conv1.weight_mask_GPU0.out &

CUDA_VISIBLE_DEVICES=2 nohup python -u main_eval_all.py --data datasets/cifar10 --dataset cifar10 --arch res18 --save_dir res18_cifar10_extreme_qrcode --pretrained pretrained_model/resnet18_lt_cifar10.pt --mask_dir ownership/res18_cifar10_qrcode_layer3.0.conv2.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar10_extreme_qrcode_layer3.0.conv2.weight_mask_GPU2.out &

CUDA_VISIBLE_DEVICES=3 nohup python -u main_eval_all.py --data datasets/cifar10 --dataset cifar10 --arch res18 --save_dir res18_cifar10_extreme_qrcode --pretrained pretrained_model/resnet18_lt_cifar10.pt --mask_dir ownership/res18_cifar10_qrcode_layer3.1.conv1.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar10_extreme_qrcode_layer3.1.conv1.weight_mask_GPU3.out &

CUDA_VISIBLE_DEVICES=4 nohup python -u main_eval_all.py --data datasets/cifar10 --dataset cifar10 --arch res18 --save_dir res18_cifar10_extreme_qrcode --pretrained pretrained_model/resnet18_lt_cifar10.pt --mask_dir ownership/res18_cifar10_qrcode_layer3.1.conv2.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar10_extreme_qrcode_layer3.1.conv2.weight_mask_GPU4.out &

CUDA_VISIBLE_DEVICES=5 nohup python -u main_eval_all.py --data datasets/cifar10 --dataset cifar10 --arch res18 --save_dir res18_cifar10_extreme_qrcode --pretrained pretrained_model/resnet18_lt_cifar10.pt --mask_dir ownership/res18_cifar10_qrcode_layer4.0.conv1.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar10_extreme_qrcode_layer4.0.conv1.weight_mask_GPU5.out &

CUDA_VISIBLE_DEVICES=6 nohup python -u main_eval_all.py --data datasets/cifar10 --dataset cifar10 --arch res18 --save_dir res18_cifar10_extreme_qrcode --pretrained pretrained_model/resnet18_lt_cifar10.pt --mask_dir ownership/res18_cifar10_qrcode_layer4.0.conv2.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar10_extreme_qrcode_layer4.0.conv2.weight_mask_GPU6.out &

CUDA_VISIBLE_DEVICES=7 nohup python -u main_eval_all.py --data datasets/cifar10 --dataset cifar10 --arch res18 --save_dir res18_cifar10_extreme_qrcode --pretrained pretrained_model/resnet18_lt_cifar10.pt --mask_dir ownership/res18_cifar10_qrcode_layer4.1.conv1.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar10_extreme_qrcode_layer4.1.conv1.weight_mask_GPU7.out &


CUDA_VISIBLE_DEVICES=0 nohup python -u main_eval_all.py --data datasets/cifar100 --dataset cifar100 --arch res18 --save_dir res18_cifar100_extreme_qrcode --pretrained res18_cifar100_lt_0.2/epoch_3.pth.tar --mask_dir ownership/res18_cifar100_qrcode_layer3.0.conv1.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar100_extreme_qrcode_layer3.0.conv1.weight_mask_GPU0.out &

CUDA_VISIBLE_DEVICES=2 nohup python -u main_eval_all.py --data datasets/cifar100 --dataset cifar100 --arch res18 --save_dir res18_cifar100_extreme_qrcode --pretrained res18_cifar100_lt_0.2/epoch_3.pth.tar --mask_dir ownership/res18_cifar100_qrcode_layer3.0.conv2.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar100_extreme_qrcode_layer3.0.conv2.weight_mask_GPU2.out &

CUDA_VISIBLE_DEVICES=3 nohup python -u main_eval_all.py --data datasets/cifar100 --dataset cifar100 --arch res18 --save_dir res18_cifar100_extreme_qrcode --pretrained res18_cifar100_lt_0.2/epoch_3.pth.tar --mask_dir ownership/res18_cifar100_qrcode_layer3.1.conv1.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar100_extreme_qrcode_layer3.1.conv1.weight_mask_GPU3.out &

CUDA_VISIBLE_DEVICES=4 nohup python -u main_eval_all.py --data datasets/cifar100 --dataset cifar100 --arch res18 --save_dir res18_cifar100_extreme_qrcode --pretrained res18_cifar100_lt_0.2/epoch_3.pth.tar --mask_dir ownership/res18_cifar100_qrcode_layer3.1.conv2.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar100_extreme_qrcode_layer3.1.conv2.weight_mask_GPU4.out &

CUDA_VISIBLE_DEVICES=5 nohup python -u main_eval_all.py --data datasets/cifar100 --dataset cifar100 --arch res18 --save_dir res18_cifar100_extreme_qrcode --pretrained res18_cifar100_lt_0.2/epoch_3.pth.tar --mask_dir ownership/res18_cifar100_qrcode_layer4.0.conv1.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar100_extreme_qrcode_layer4.0.conv1.weight_mask_GPU5.out &

CUDA_VISIBLE_DEVICES=6 nohup python -u main_eval_all.py --data datasets/cifar100 --dataset cifar100 --arch res18 --save_dir res18_cifar100_extreme_qrcode --pretrained res18_cifar100_lt_0.2/epoch_3.pth.tar --mask_dir ownership/res18_cifar100_qrcode_layer4.0.conv2.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar100_extreme_qrcode_layer4.0.conv2.weight_mask_GPU6.out &

CUDA_VISIBLE_DEVICES=7 nohup python -u main_eval_all.py --data datasets/cifar100 --dataset cifar100 --arch res18 --save_dir res18_cifar100_extreme_qrcode --pretrained res18_cifar100_lt_0.2/epoch_3.pth.tar --mask_dir ownership/res18_cifar100_qrcode_layer4.1.conv1.weight_mask.pth.tar --fc --lr 0.1 --seed 1 --save_model --prune-type lt --type identity > 0521_res18_cifar100_extreme_qrcode_layer4.1.conv1.weight_mask_GPU7.out &

CUDA_VISIBLE_DEVICES=3 python -u main_eval_all.py --data datasets/cifar100 --dataset cifar100 --arch res18 --save_dir test --pretrained pretrained_model/epoch_3.pth.tar --mask_dir res18_cifar10_lt_0.01/6model_SA_best.pth.tar --fc --evaluate --checkpoint res18_cifar100_lt_0.2_continue/17model_SA_best.pth.tar